### PR TITLE
chore: make react-hooks/exhaustive-deps eslint rule error vs. warn

### PR DESCRIPTION
**Pull request by blimmer**
[sc-40033]

https://homeboundinc.slack.com/archives/C012SEYSQGG/p1694472845039779

I used a codemod to supress all existing errors:

> npx suppress-eslint-errors ./src --extensions=ts,tsx --parser=tsx --rules=react-hooks/exhaustive-deps --message="TODO: validate this eslint-disable. It was automatically ignored as part of https://app.shortcut.com/homebound-team/story/40033/enable-react-hooks-exhaustive-deps-for-internal-frontend"

I also used a simple regex replace to clean up the comments:

```
\}, (\/\/ TODO: validate.*)
}, \n $1
```

Screenshot 2023-09-13 at 12 48 06

Then, finally, run `yarn lint:fix` (or commit to get the pre-commit hook) to run prettier.

### CODE REVIEW

**Comment by blimmer** [comment]
@bdow - there was never a lint step in CI for this project, so I added one. I didn't disable these existing errors:

```
/Users/blimmer/code/homebound/beam/src/components/Table/GridTable.test.tsx
  3137:13  error  Avoid wrapping Testing Library util calls in `act`  testing-library/no-unnecessary-act
  3219:13  error  Avoid wrapping Testing Library util calls in `act`  testing-library/no-unnecessary-act

/Users/blimmer/code/homebound/beam/src/components/internal/MenuItem.tsx
  33:15  error  React Hook "useRef" is called conditionally. React Hooks must be called in the exact same order in every component render       react-hooks/rules-of-hooks
  34:19  error  React Hook "useHistory" is called conditionally. React Hooks must be called in the exact same order in every component render   react-hooks/rules-of-hooks
  35:37  error  React Hook "useHover" is called conditionally. React Hooks must be called in the exact same order in every component render     react-hooks/rules-of-hooks
  36:15  error  React Hook "useTestIds" is called conditionally. React Hooks must be called in the exact same order in every component render   react-hooks/rules-of-hooks
  37:29  error  React Hook "useMenuItem" is called conditionally. React Hooks must be called in the exact same order in every component render  react-hooks/rules-of-hooks

/Users/blimmer/code/homebound/beam/src/inputs/TreeSelectField/TreeOption.tsx
  26:15  error  React Hook "useRef" is called conditionally. React Hooks must be called in the exact same order in every component render                      react-hooks/rules-of-hooks
  27:37  error  React Hook "useHover" is called conditionally. React Hooks must be called in the exact same order in every component render                    react-hooks/rules-of-hooks
  28:15  error  React Hook "useTestIds" is called conditionally. React Hooks must be called in the exact same order in every component render                  react-hooks/rules-of-hooks
  30:63  error  React Hook "useTreeSelectFieldProvider" is called conditionally. React Hooks must be called in the exact same order in every component render  react-hooks/rules-of-hooks
  32:62  error  React Hook "useOption" is called conditionally. React Hooks must be called in the exact same order in every component render                   react-hooks/rules-of-hooks

/Users/blimmer/code/homebound/beam/src/utils/rtl.test.tsx
  218:6  error  Test title is used multiple times in the same describe block  jest/no-identical-title

✖ 13 problems (13 errors, 0 warnings)
```

Do you want me to disable them? Or do you (or someone else) want to look at it?

**Review by stephenh — APPROVED** [review]
:tada:

**Comment by bdow** [comment]
> Do you want me to disable them? Or do you (or someone else) want to look at it?

Let's disable them for now. If you don't mind, could you write a ticket and assign it to me I can take it from there. Thanks!

**Comment by blimmer** [comment]
Yep, can do.

**Comment by blimmer** [comment]
@bdow https://app.shortcut.com/homebound-team/story/40045

**Pull request merged**
