### PR TITLE
fix: Fix Virtuoso 'Zero-sized element' error

### PR DESCRIPTION
**Pull request by bdow**

### CODE REVIEW

**Review by chr1sjf0x — APPROVED** [review]
Amazing!! TY 🎉 

I wonder if this fixed the scrolling jank 🤔

**Comment by bdow** [comment]
> Amazing!! TY 🎉
> 
> I wonder if this fixed the scrolling jank 🤔

It might!

**Review by stephenh — APPROVED** [review]
Nice!

FWIW I wonder if we should just straight-up remove the `display: contents` specifically for the virutalized rendering. I'd like to keep it for the non-virtualized for a little bit.

**Comment by bdow** [comment]
> Nice!
> 
> FWIW I wonder if we should just straight-up remove the `display: contents` specifically for the virutalized rendering. I'd like to keep it for the non-virtualized for a little bit.

Oh yea, thats a good question. I'll see what happens...

**Pull request merged**
